### ISSUE TITLE
interceptEvents doesnt catch  shadowDom links events

### ISSUE THREAD

**Issue by ar2r13** [virtualstate/navigation#14]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Version (i.e. v2.x.x)

1.0.1-alpha.192

### Operating system

None

### Description

interceptEvents doesnt catch  shadowDom links events.

function interceptWindowClicks() checks only parents of event target. I guess it would be better to check is event path contains any a[href]

### Steps to Reproduce

```js
import('@virtualstate/navigation').then(({ applyPolyfill }) => applyPolyfill({
    interceptEvents: true
}))

### Expected Behavior

_No response_

**Comment by fabiancook** [comment]
Thanks I will look into this specific case!

Do you have a static html page that can trigger the issue? If you can make a PR, starting from 

https://github.com/virtualstate/navigation/blob/17132f9caabf98ee76fad459841e9c649346921b/example/index.html#L1-L84

I will then be able to load this up in playwright and trigger the behaviour, and make a test around it like this, and will also be able to load it up directly in a browser and see how the behaviour works. Cheers!

(Sorry for the late reply I have been on holiday for the last month so haven't seen any github notifications!)

**Comment by fabiancook** [comment]
With the changes from #17, this should be good to go from here. I tested this in safari, I'll add some playwright tests to match though in the near future. 

-----------------

Some non important but informational bits....

In the image below the target of the `originalEvent` is `<link-element>`, an element with a shadow dom:

```typescript
class LinkElement extends HTMLElement {
  constructor() {
    super();
    const shadow = this.attachShadow({ mode: "open" });
    shadow.innerHTML = '<a href="/">Link within Shadow DOM</a>';
  }
}

window.customElements.define('link-element', LinkElement)
```

![image](https://github.com/virtualstate/navigation/assets/4337080/e221b693-2fb6-45f2-9588-c77d803996f7)

Using [`composedPath()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath)

![image](https://github.com/virtualstate/navigation/assets/4337080/29d784bb-c14f-4438-ab7e-ad6d6f104c0a)

If we inspect targets we can see the inner anchor element being accessible. 

```typescript
function getComposedPathTarget(event) {
    if (!event.composedPath) {
        return event.target;
    }
    const targets = event.composedPath();
    return targets[0] ?? event.target;
}
```
![image](https://github.com/virtualstate/navigation/assets/4337080/b0d312be-8c7f-4337-8953-857afc080a49)

 This only accounts for shadow DOM's using open mode.
