### ISSUE TITLE
Mark `sideEffects`

### ISSUE THREAD

**Issue by TomokiMiyauci** [virtualstate/navigation#28]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Version (i.e. v2.x.x)

v1.0.1-alpha.95

### Operating system

None

### Description

If `sideEffects` in package.json is `false`, the bundler will remove the following:

```ts
import "@virtualstate/navigation/polyfill";.
```

The `sideEffects` field must be removed or the sideEffects file must be enumerated.

### Steps to Reproduce

bundle it

### Expected Behavior

Reference:

For example, [urlpattern-polyfill](https://github.com/kenchris/urlpattern-polyfill) has no `sideEffects` field.

**Comment by fabiancook** [comment]
Makes sense!
